export const MOVIE_LIBRARY = [
  {
    id: 101,
    title: 'Dune: Part Two',
    tagline: 'The desert demands a new destiny.',
    summary:
      'Paul Atreides unites with the Fremen to fight for Arrakis while facing betrayal, prophecy, and a brutal war for the spice.',
    releaseDate: '2024-03-15',
    runtime: 166,
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    tags: ['space opera', 'desert', 'epic', 'political', 'sandworms'],
    directors: ['Denis Villeneuve'],
    actors: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
    producers: ['Mary Parent', 'Denis Villeneuve', 'Cale Boyter'],
    poster: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/Way9Dexny3w',
    videoTitle: 'Official Trailer',
    contentType: 'Movie',
    isAnime: false,
    hasManga: false,
    hasManhwa: false,
    isSeries: false,
    seriesStatus: 'Standalone film',
    whereToWatch: [
      { name: 'Netflix', url: 'https://www.netflix.com/' },
      { name: 'Prime Video', url: 'https://www.primevideo.com/' },
    ],
    related: [102, 103, 104],
  },
  {
    id: 102,
    title: 'Spider-Man: Across the Spider-Verse',
    tagline: 'The multiverse is bigger than you think.',
    summary:
      'Miles Morales races across the multiverse with Gwen Stacy as he confronts a new villain and learns what it means to be a hero in a universe that is constantly changing.',
    releaseDate: '2023-06-02',
    runtime: 140,
    genres: ['Animation', 'Action', 'Adventure'],
    tags: ['superhero', 'multiverse', 'coming-of-age', 'comic-book', 'animation'],
    directors: ['Joaquim Dos Santos', 'Kemp Powers', 'Justin K. Thompson'],
    actors: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Brian Tyree Henry'],
    producers: ['Avi Arad', 'Phil Lord', 'Christopher Miller'],
    poster: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/cqGjhVJWtEg',
    videoTitle: 'Official Trailer',
    contentType: 'Movie',
    isAnime: false,
    hasManga: false,
    hasManhwa: false,
    isSeries: false,
    seriesStatus: 'Part of the Spider-Verse saga',
    whereToWatch: [
      { name: 'Disney+', url: 'https://www.disneyplus.com/' },
      { name: 'Apple TV', url: 'https://tv.apple.com/' },
    ],
    related: [101, 103, 105],
  },
  {
    id: 103,
    title: 'Your Name',
    tagline: 'Fate threads two lives together.',
    summary:
      'Two teenagers discover that their bodies are mysteriously swapped, leading to a deeply emotional journey through time, memory, and fate.',
    releaseDate: '2016-08-26',
    runtime: 106,
    genres: ['Animation', 'Drama', 'Romance'],
    tags: ['anime', 'romance', 'time-travel', 'emotion', 'coming-of-age'],
    directors: ['Makoto Shinkai'],
    actors: ['Ryûnosuke Kamiki', 'Mone Kamishiraishi', 'Masami Nagasawa'],
    producers: ['Genki Kawamura'],
    poster: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/xU47nhruN-Q',
    videoTitle: 'Official Trailer',
    contentType: 'Anime',
    isAnime: true,
    hasManga: false,
    hasManhwa: false,
    isSeries: false,
    seriesStatus: 'Standalone anime film',
    whereToWatch: [
      { name: 'Crunchyroll', url: 'https://www.crunchyroll.com/' },
      { name: 'Netflix', url: 'https://www.netflix.com/' },
    ],
    related: [104, 107, 109],
  },
  {
    id: 104,
    title: 'Solo Leveling',
    tagline: 'Weakness is not a destiny.',
    summary:
      'A world teeming with monsters forces a weak hunter into a brutal power struggle as he uncovers a secret that rewrites his path.',
    releaseDate: '2024-01-07',
    runtime: 45,
    genres: ['Action', 'Fantasy', 'Adventure'],
    tags: ['anime', 'webtoon', 'hunting', 'monster', 'power fantasy'],
    directors: ['Tatsuya Sasaki'],
    actors: ['Ahn Hyeon-woo', 'Lee Min-hyuk', 'Yoo Soo-bin'],
    producers: ['Aniplex'],
    poster: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/0M8G9K-0YHU',
    videoTitle: 'Official Teaser',
    contentType: 'Anime Series',
    isAnime: true,
    hasManga: true,
    hasManhwa: true,
    isSeries: true,
    seriesStatus: 'Ongoing / Season 1 available',
    whereToWatch: [
      { name: 'Crunchyroll', url: 'https://www.crunchyroll.com/' },
      { name: 'Amazon Prime', url: 'https://www.primevideo.com/' },
    ],
    related: [103, 109, 110],
  },
  {
    id: 105,
    title: 'Attack on Titan',
    tagline: 'Freedom is worth the cost of everything.',
    summary:
      'Humanity hides behind walls while giant titans threaten their existence. A desperate struggle for survival turns into a fight to reclaim the world.',
    releaseDate: '2013-04-07',
    runtime: 24,
    genres: ['Action', 'Drama', 'Fantasy'],
    tags: ['anime', 'post-apocalyptic', 'dark fantasy', 'war', 'survival'],
    directors: ['Tetsuro Araki'],
    actors: ['Yuki Kaji', 'Eren Jaeger', 'Hiroshi Kamiya', 'Marina Inoue'],
    producers: ['Wit Studio', 'MAPPA'],
    poster: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/MGRm4XaK-Zo',
    videoTitle: 'Season Trailer',
    contentType: 'Anime Series',
    isAnime: true,
    hasManga: true,
    hasManhwa: false,
    isSeries: true,
    seriesStatus: 'Completed',
    whereToWatch: [
      { name: 'Crunchyroll', url: 'https://www.crunchyroll.com/' },
      { name: 'Netflix', url: 'https://www.netflix.com/' },
    ],
    related: [104, 107, 110],
  },
  {
    id: 106,
    title: 'The Batman',
    tagline: 'The city is watching.',
    summary:
      'Batman investigates a string of murders in Gotham as he confronts corruption, fear, and the legacy of his own trauma.',
    releaseDate: '2022-03-04',
    runtime: 176,
    genres: ['Crime', 'Action', 'Thriller'],
    tags: ['dc', 'detective', 'gotham', 'noir', 'superhero'],
    directors: ['Matt Reeves'],
    actors: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Jeffrey Wright'],
    producers: ['Matt Reeves', ' Dylan Clark'],
    poster: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/mqqft2x_Aa4',
    videoTitle: 'Official Trailer',
    contentType: 'Movie',
    isAnime: false,
    hasManga: false,
    hasManhwa: false,
    isSeries: false,
    seriesStatus: 'Batman universe',
    whereToWatch: [
      { name: 'HBO Max', url: 'https://play.hbomax.com/' },
      { name: 'Prime Video', url: 'https://www.primevideo.com/' },
    ],
    related: [102, 101, 110],
  },
  {
    id: 107,
    title: 'The Witcher',
    tagline: 'Monsters are real. So is destiny.',
    summary:
      'Geralt of Rivia crosses paths with a sorceress, a princess, and a monster-hunting destiny that grips a fractured continent.',
    releaseDate: '2019-12-20',
    runtime: 60,
    genres: ['Fantasy', 'Action', 'Drama'],
    tags: ['series', 'dark fantasy', 'monster hunter', 'magic', 'adaptation'],
    directors: ['Lauren Schmidt Hissrich'],
    actors: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan', 'Joey Batey'],
    producers: ['Tomasz Bagiński', 'Lauren Schmidt Hissrich'],
    poster: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/ndl1W4ltcmg',
    videoTitle: 'Official Trailer',
    contentType: 'Series',
    isAnime: false,
    hasManga: false,
    hasManhwa: false,
    isSeries: true,
    seriesStatus: 'Ongoing / latest season released',
    whereToWatch: [
      { name: 'Netflix', url: 'https://www.netflix.com/' },
      { name: 'YouTube', url: 'https://www.youtube.com/' },
    ],
    related: [105, 110, 108],
  },
  {
    id: 108,
    title: 'The Boy and the Heron',
    tagline: 'A journey beyond memory.',
    summary:
      'After a family tragedy, a young boy follows a mysterious heron into a magical world that reshapes his understanding of life, grief, and courage.',
    releaseDate: '2023-11-17',
    runtime: 124,
    genres: ['Animation', 'Fantasy', 'Drama'],
    tags: ['anime', 'family', 'magic', 'coming-of-age', 'masterpiece'],
    directors: ['Hayao Miyazaki'],
    actors: ['Soma Santoki', 'Masaki Suda', 'Aimyon'],
    producers: ['Toshio Suzuki'],
    poster: 'https://images.unsplash.com/photo-1524989942931-7f1d4f7d68b6?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/0pVkiod6V0U',
    videoTitle: 'Official Trailer',
    contentType: 'Anime',
    isAnime: true,
    hasManga: false,
    hasManhwa: false,
    isSeries: false,
    seriesStatus: 'Standalone film',
    whereToWatch: [
      { name: 'Max', url: 'https://play.max.com/' },
      { name: 'Crunchyroll', url: 'https://www.crunchyroll.com/' },
    ],
    related: [103, 105, 109],
  },
  {
    id: 109,
    title: 'One Piece',
    tagline: 'A pirate dream is bigger than the sea.',
    summary:
      'Monkey D. Luffy sets sail to become the King of the Pirates, gathering a crew of dreamers and fighters across a vast world of adventure.',
    releaseDate: '1999-10-20',
    runtime: 24,
    genres: ['Adventure', 'Fantasy', 'Comedy'],
    tags: ['anime', 'pirates', 'adventure', 'friendship', 'epic'],
    directors: ['Eiichiro Oda'],
    actors: ['Mayumi Tanaka', 'Kazuya Nakai', 'Akemi Okamura'],
    producers: ['Toei Animation'],
    poster: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/4sF-ABK88bY',
    videoTitle: 'Main Trailer',
    contentType: 'Anime Series',
    isAnime: true,
    hasManga: true,
    hasManhwa: false,
    isSeries: true,
    seriesStatus: 'Ongoing',
    whereToWatch: [
      { name: 'Crunchyroll', url: 'https://www.crunchyroll.com/' },
      { name: 'Netflix', url: 'https://www.netflix.com/' },
    ],
    related: [104, 108, 105],
  },
  {
    id: 110,
    title: 'The Last of Us',
    tagline: 'Humanity is not the only thing left behind.',
    summary:
      'A hardened survivor escorts a teenage girl across a devastated America, fighting to stay alive while protecting the last sparks of hope.',
    releaseDate: '2023-01-15',
    runtime: 55,
    genres: ['Drama', 'Action', 'Thriller'],
    tags: ['series', 'post-apocalyptic', 'survival', 'emotional', 'zombies'],
    directors: ['Craig Mazin'],
    actors: ['Pedro Pascal', 'Bella Ramsey', 'Gabriel Luna'],
    producers: ['Neil Druckmann', 'Carolyn Strauss'],
    poster: 'https://images.unsplash.com/photo-1524989942931-7f1d4f7d68b6?auto=format&fit=crop&w=900&q=80',
    backdrop:
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1400&q=80',
    trailerUrl: 'https://www.youtube.com/embed/8w7euNte0A8',
    videoTitle: 'Series Trailer',
    contentType: 'Series',
    isAnime: false,
    hasManga: false,
    hasManhwa: false,
    isSeries: true,
    seriesStatus: 'A second season is in progress',
    whereToWatch: [
      { name: 'HBO Max', url: 'https://play.hbomax.com/' },
      { name: 'Prime Video', url: 'https://www.primevideo.com/' },
    ],
    related: [107, 106, 105],
  },
];

export const searchMovieLibrary = (query = '') => {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return MOVIE_LIBRARY.slice(0, 8);
  }

  return MOVIE_LIBRARY.filter((movie) => {
    const searchableText = [
      movie.title,
      movie.summary,
      movie.tagline,
      movie.contentType,
      movie.seriesStatus,
      ...movie.genres,
      ...movie.tags,
      ...movie.directors,
      ...movie.actors,
      ...movie.producers,
    ]
      .join(' ')
      .toLowerCase();

    return searchableText.includes(normalized);
  });
};

export const getTrendingMovies = () => MOVIE_LIBRARY.slice(0, 5);

export const getMovieById = (movieId) =>
  MOVIE_LIBRARY.find((movie) => movie.id === Number(movieId)) || MOVIE_LIBRARY[0];
